@extends('layouts.app')
@section('title', 'Campus food, on your time')
@section('content')
<x-promotion-strip :promotions="$promotions" />
@if($mealOfTheWeek)
    <section class="meal-of-week-banner">
        <img src="{{ $mealOfTheWeek->image_url ?: '/images/meal-placeholder.svg' }}" alt="{{ $mealOfTheWeek->name }}" onerror="this.onerror=null;this.src='/images/meal-placeholder.svg'">
        <div><span class="manage-kicker">STUDENT-VOTED MEAL OF THE WEEK</span><h2>{{ $mealOfTheWeek->name }}</h2><p>Chosen by ATU customers. Try this campus favourite from {{ $mealOfTheWeek->vendor?->name ?? 'ATU Eats' }}.</p><form action="{{ route('cart.add', $mealOfTheWeek) }}" method="POST">@csrf<button class="manage-button" type="submit">Add winning meal to cart <span aria-hidden="true">&rarr;</span></button></form></div>
    </section>
@endif
<section class="hero-wrap"><div class="hero-copy"><div class="eyebrow"><span class="eyebrow-dot"></span> YOUR CAMPUS, SERVED FRESH</div><h1>Good <em>food.</em></h1><p>Order your favourites ahead and pick them up fresh. Your next lecture doesn’t have to wait in line.</p><div class="hero-actions"><a class="button button-primary" href="{{ route('menu') }}">Find your next meal <span>↗</span></a><a class="text-link" href="#how-it-works">How it works <span>↓</span></a></div><div class="hero-note"><div class="mini-avatars"><span>J</span><span>A</span><span>K</span></div><span><b>Made for the ATU community</b><br>Good food, right around your schedule.</span></div></div><div class="hero-visual"><img src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1150&q=88" alt="Fresh colourful campus lunch bowl"><div class="image-tag"><span class="tag-icon">✳</span><span><b>Freshly prepared</b><small>Ready for your pickup</small></span></div><div class="floating-stamp">YOUR<br>CAMPUS<br>FAVOURITE <span>✳</span></div></div></section>
<section class="trust-strip"><div><span class="trust-icon">◷</span><span><b>Skip the queue</b><small>Order before the rush</small></span></div><i></i><div><span class="trust-icon">✳</span><span><b>Made fresh daily</b><small>Campus favourites, always</small></span></div><i></i><div><span class="trust-icon">⌖</span><span><b>Easy pickup</b><small>Collect between classes</small></span></div><a href="{{ route('menu') }}">See what’s cooking <span>↗</span></a></section>
<section class="section atu-favorites-section"><div class="section-heading"><div><div class="eyebrow">CHOSEN BY ATU CUSTOMERS</div><h2>ATU <em>favourites.</em></h2></div><a class="text-link" href="{{ route('menu') }}">Explore the full menu <span>&rarr;</span></a></div>
@if($atuFavorites->isNotEmpty())
<div class="food-grid">
    @foreach($atuFavorites as $food)
        @php($foodRatingAverage = collect([$food->portion_rating_average, $food->value_rating_average, $food->accuracy_rating_average])->filter(fn ($rating) => $rating !== null)->avg())
        <article class="food-card"><div class="food-image"><img src="{{ $food->image_url ?: '/images/meal-placeholder.svg' }}" alt="{{ $food->name }}" loading="lazy" onerror="this.onerror=null;this.src='/images/meal-placeholder.svg'"><span class="food-label">ATU FAVOURITE</span><x-meal-save-button :food="$food" :is-saved="in_array($food->id, $favoriteFoodIds)" /></div><div class="food-info"><div><h3>{{ $food->name }}</h3><div class="favorite-score"><span aria-hidden="true">&#9733;</span> {{ number_format($foodRatingAverage, 1) }} <small>{{ $food->reviews_count }} verified {{ Str::plural('rating', $food->reviews_count) }}</small></div><p>{{ $food->description ?: 'A campus favourite, prepared fresh for you.' }}</p></div><div class="food-bottom"><strong><x-money :amount="$food->price" /></strong><form action="{{ route('cart.add', $food) }}" method="POST">@csrf<button class="add-button" aria-label="Add {{ $food->name }} to cart">+</button></form></div></div></article>
    @endforeach
</div>
@else
<div class="atu-favorites-empty"><span aria-hidden="true">&#9733;</span><div><strong>The first ATU favourites are taking shape.</strong><p>Once customers rate completed meals, top-rated plates will appear here.</p></div><a href="{{ route('menu') }}">Browse meals &amp; rate your picks <span aria-hidden="true">&rarr;</span></a></div>
@endif
</section>
<section class="section featured-section"><div class="section-heading"><div><div class="eyebrow">A LITTLE TASTE OF ATU</div><h2>Good things on <em>the menu.</em></h2></div><a class="text-link" href="{{ route('menu') }}">Browse all meals <span>↗</span></a></div><div class="food-grid">
@forelse($foods as $food)
<article class="food-card"><div class="food-image"><img src="{{ $food->image_url ?: '/images/meal-placeholder.svg' }}" alt="{{ $food->name }}" loading="lazy" onerror="this.onerror=null;this.src='/images/meal-placeholder.svg'"><span class="food-label">STUDENT FAVOURITE</span><x-meal-save-button :food="$food" :is-saved="in_array($food->id, $favoriteFoodIds)" /></div><div class="food-info"><div><h3>{{ $food->name }}</h3>@if($food->reviews_count)@php($foodRatingAverage = collect([$food->portion_rating_average, $food->value_rating_average, $food->accuracy_rating_average])->filter(fn ($rating) => $rating !== null)->avg())<div class="food-rating" aria-label="ATU customer verified rating">&#9733; {{ number_format($foodRatingAverage, 1) }} <small>{{ $food->reviews_count }} verified</small></div>@endif<p>{{ $food->description }}</p></div><div class="food-bottom"><strong><x-money :amount="$food->price" /></strong><form action="{{ route('cart.add', $food) }}" method="POST">@csrf<button class="add-button" aria-label="Add {{ $food->name }} to cart">+</button></form></div></div></article>
@empty
<div class="empty-featured"><span>✳</span><h3>Fresh plates are on the way.</h3><p>Check back soon for today’s campus favourites.</p></div>
@endforelse
</div></section>
<section class="how-section" id="how-it-works"><div class="how-intro"><div class="eyebrow">A BETTER LUNCH BREAK</div><h2>Your meal,<br><em>your moment.</em></h2><p>More time to eat, catch up and get where you’re going. Ordering ahead is easy.</p><a class="button button-light" href="{{ route('menu') }}">Let’s get lunch <span>↗</span></a></div><div class="steps"><div class="step"><span>01</span><div><h3>Pick your plate</h3><p>Explore delicious campus favourites, made fresh for you.</p></div><b>↗</b></div><div class="step"><span>02</span><div><h3>Choose your pickup</h3><p>Place your order and choose a time that fits your day.</p></div><b>↗</b></div><div class="step"><span>03</span><div><h3>Collect & enjoy</h3><p>Head to the pickup point and get on with the good stuff.</p></div><b>↗</b></div></div></section>
<section class="closing-cta"><span class="closing-flower">✳</span><div><div class="eyebrow">LUNCH PLANS, SORTED</div><h2>Ready when <em>you are.</em></h2></div><a class="button button-primary" href="{{ route('menu') }}">Explore the menu <span>↗</span></a></section>
@endsection
