databases:
  - name: atu-eats-demo-db
    databaseName: atu_eats
    user: atu_eats
    plan: free
    region: frankfurt

services:
  - type: web
    name: atu-eats-demo
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /up
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: ATU Eats
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Africa/Accra
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: atu-eats-demo-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: SUPPORT_EMAIL
        value: kencrespo1011@gmail.com
      - key: SUPPORT_PHONE
        value: 0575732548
      - key: PAYSTACK_SECRET_KEY
        sync: false
