@extends('layouts.app')
@section('title', $customer->name)
@section('content')
<section class="manage-shell"><a class="manage-text-link admin-back-link" href="{{ route('admin.customers.index') }}">← Customer directory</a><div class="manage-hero admin-detail-hero"><div><span class="manage-kicker">CUSTOMER PROFILE</span><h1>{{ $customer->name }}</h1><p>Customer since {{ $customer->created_at->format('F j, Y') }}</p></div></div>
<div class="manage-stats"><article><small>Total orders</small><strong>{{ $customer->orders()->count() }}</strong></article><article><small>Total order value</small><strong><x-money :amount="$customer->orders()->sum('total')" /></strong></article><article><small>Account status</small><strong>{{ $customer->is_active ? 'Active' : 'Inactive' }}</strong></article><article><small>Customer ID</small><strong>#{{ $customer->id }}</strong></article></div>
<section class="manage-panel"><div class="manage-title"><div><span class="manage-kicker">CUSTOMER CONTACT</span><h2>Account information</h2></div></div><div class="admin-contact-grid"><div><small>Email address</small><a href="mailto:{{ $customer->email }}">{{ $customer->email }}</a></div><div><small>Phone number</small>@if($customer->phone)<a href="tel:{{ $customer->phone }}">{{ $customer->phone }}</a>@else<span>Not provided</span>@endif</div></div></section>
<section class="manage-panel admin-section-spaced"><div class="manage-title"><div><span class="manage-kicker">ORDER HISTORY</span><h2>Customer orders</h2></div><a class="manage-text-link" href="{{ route('admin.orders.index', ['q' => $customer->name]) }}">Search all orders →</a></div>
@forelse($orders as $order)<a class="admin-order-row" href="{{ route('admin.orders.show', $order) }}"><span class="admin-order-number">#{{ str_pad($order->id, 5, '0', STR_PAD_LEFT) }}</span><span>{{ $order->items->pluck('food_name')->join(', ') ?: 'No meal details' }}<small>{{ $order->created_at->format('M j, Y · g:i A') }}</small></span><span class="manage-status status-{{ $order->status }}">{{ ucfirst($order->status) }}</span><strong><x-money :amount="$order->total" /></strong><b>›</b></a>@empty<p class="manage-empty">This customer has not placed any orders yet.</p>@endforelse{{ $orders->links() }}</section>
</section>
@endsection
