@extends('layouts.app')
@section('title', 'Order #'.str_pad($order->id, 5, '0', STR_PAD_LEFT))
@section('content')
<section class="manage-shell"><a class="manage-text-link admin-back-link" href="{{ route('admin.orders.index') }}">← All orders</a><div class="manage-hero admin-detail-hero"><div><span class="manage-kicker">ORDER #{{ str_pad($order->id, 5, '0', STR_PAD_LEFT) }}</span><h1>{{ $order->user->name }}</h1><p>Placed {{ $order->created_at->format('F j, Y · g:i A') }} · Pickup {{ $order->pickup_time->format('F j · g:i A') }}</p></div><span class="manage-status status-{{ $order->status }}">{{ ucfirst($order->status) }}</span></div>
<div class="manage-stats"><article><small>Order total</small><strong>GH&#8373; {{ number_format($order->total, 2) }}</strong></article><article><small>Customer</small><strong>{{ $order->user->name }}</strong></article><article><small>Order status</small><strong>{{ ucfirst($order->status) }}</strong></article><article><small>Number of meals</small><strong>{{ $order->items->sum('quantity') }}</strong></article></div>
<section class="manage-panel"><div class="manage-title"><div><span class="manage-kicker">CUSTOMER DETAILS</span><h2>Contact and pickup</h2></div><a class="manage-text-link" href="{{ route('admin.customers.show', $order->user) }}">View customer profile →</a></div><div class="admin-contact-grid"><div><small>Email address</small><a href="mailto:{{ $order->user->email }}">{{ $order->user->email }}</a></div><div><small>Phone number</small>@if($order->user->phone)<a href="tel:{{ $order->user->phone }}">{{ $order->user->phone }}</a>@else<span>Not provided</span>@endif</div><div><small>Pickup time</small><span>{{ $order->pickup_time->format('l, F j · g:i A') }}</span></div><div><small>Order placed</small><span>{{ $order->created_at->format('l, F j · g:i A') }}</span></div></div>@if($order->notes)<p class="admin-order-note"><strong>Customer note:</strong> {{ $order->notes }}</p>@endif</section>
<section class="manage-panel admin-section-spaced"><div class="manage-title"><div><span class="manage-kicker">ORDER CONTENTS</span><h2>Meals and vendors</h2></div></div>@forelse($order->items as $item)<div class="admin-order-row"><span class="vendor-avatar">{{ $item->quantity }}×</span><span>{{ $item->food_name }}<small>Vendor: {{ $item->vendor?->name ?? 'Unassigned' }}{{ $item->vendor?->phone ? ' · '.$item->vendor->phone : '' }}</small></span><span class="manage-status status-{{ $item->status }}">{{ ucfirst($item->status) }}</span><strong>GH&#8373; {{ number_format($item->price * $item->quantity, 2) }}</strong></div>@empty<p class="manage-empty">No meal details were recorded for this order.</p>@endforelse<div class="summary-total"><span>Order total</span><strong>GH&#8373; {{ number_format($order->total, 2) }}</strong></div></section>
</section>
@endsection
