@extends('layouts.app')
@section('title', $vendor->name)
@section('content')
<section class="manage-shell"><a class="manage-text-link admin-back-link" href="{{ route('admin.vendors.index') }}">← Vendor performance</a><div class="manage-hero admin-detail-hero"><div><span class="manage-kicker">VENDOR PROFILE</span><h1>{{ $vendor->name }}</h1><p>{{ $vendor->is_active ? 'Active vendor' : 'Vendor access is paused' }} · Added {{ $vendor->created_at->format('F j, Y') }}</p></div><form method="POST" action="{{ route('admin.vendors.status', $vendor) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $vendor->is_active ? 0 : 1 }}"><button class="manage-button" type="submit">{{ $vendor->is_active ? 'Pause access' : 'Reactivate vendor' }}</button></form></div>
<div class="manage-stats"><article><small>Menu meals</small><strong>{{ $vendor->foods_count }}</strong></article><article><small>Orders</small><strong>{{ $performance->orders_count ?? 0 }}</strong></article><article><small>Meals sold</small><strong>{{ $performance->meals_sold ?? 0 }}</strong></article><article><small>Sales</small><strong>GH&#8373; {{ number_format($performance->revenue ?? 0, 2) }}</strong></article></div>
<section class="manage-panel"><div class="manage-title"><div><span class="manage-kicker">VENDOR CONTACT</span><h2>Account information</h2></div></div><div class="admin-contact-grid"><div><small>Phone sign-in</small><a href="tel:{{ $vendor->phone }}">{{ $vendor->phone ?: 'Not provided' }}</a></div><div><small>Account status</small><span>{{ $vendor->is_active ? 'Active' : 'Paused' }}</span></div></div></section>
<section class="manage-panel admin-section-spaced"><div class="manage-title"><div><span class="manage-kicker">VENDOR MENU</span><h2>Meals managed by vendor</h2></div></div>@forelse($foods as $food)<div class="admin-order-row"><span class="vendor-avatar">{{ strtoupper(substr($food->name, 0, 1)) }}</span><span>{{ $food->name }}<small>{{ $food->description ?: 'No description' }}</small></span><span class="manage-status {{ $food->available ? 'status-ready' : 'status-received' }}">{{ $food->available ? 'Available' : 'Unavailable' }}</span><strong>GH&#8373; {{ number_format($food->price, 2) }}</strong></div>@empty<p class="manage-empty">This vendor has not added any meals yet.</p>@endforelse</section>
<section class="manage-panel admin-section-spaced"><div class="manage-title"><div><span class="manage-kicker">FULFILMENT ACTIVITY</span><h2>Vendor order items</h2></div></div>@forelse($orders as $item)<a class="admin-order-row" href="{{ route('admin.orders.show', $item->order) }}"><span class="admin-order-number">#{{ str_pad($item->order_id, 5, '0', STR_PAD_LEFT) }}</span><span>{{ $item->food_name }} × {{ $item->quantity }}<small>{{ $item->order->user->name }} · {{ $item->created_at->format('M j, Y · g:i A') }}</small></span><span class="manage-status status-{{ $item->status }}">{{ ucfirst($item->status) }}</span><strong>GH&#8373; {{ number_format($item->price * $item->quantity, 2) }}</strong><b>›</b></a>@empty<p class="manage-empty">No orders for this vendor yet.</p>@endforelse{{ $orders->links() }}</section>
</section>
@endsection
